name: arkit_plugin
description: Flutter Plugin for ARKit - Apple's augmented reality (AR) development platform for iOS mobile devices.
version: 1.1.2
repository: https://github.com/olexale/arkit_flutter_plugin
issue_tracker: https://github.com/olexale/arkit_flutter_plugin/issues
topics:
  - ar
  - arkit

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  vector_math: ^2.1.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ArkitPlugin
