name: arkit_plugin
description: Flutter Plugin for ARKit - Apple's augmented reality (AR) development platform for iOS mobile devices.
version: 0.6.0
author: Oleksandr Leuschenko <olexa.le@gmail.com>
homepage: https://github.com/olexale/arkit_flutter_plugin

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  vector_math: ^2.0.8
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  json_serializable: ^3.3.0
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ArkitPlugin
